from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json

_session = None

def connect_database():
    # This secure connect bundle is autogenerated when you download your SCB, 
    # if yours is different update the file name below
    global _session
    if _session is not None:
        return _session

    cloud_config= {
    'secure_connect_bundle': 'secure-connect-ex4.zip'
    }

    # This token JSON file is autogenerated when you download your token, 
    # if yours is different update the file name below
    with open("ex4-token.json") as f:
        secrets = json.load(f)

    CLIENT_ID = secrets["clientId"]
    CLIENT_SECRET = secrets["secret"]

    auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
    cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
    _session = cluster.connect()
    return _session


# row = session.execute("select release_version from system.local").one()
# if row:
#   print(row[0])
# else:
#   print("An error occurred.")